project_id = "yfezwmgsudmthpcjpbdn"

[functions.deploy-project]
enabled = true
verify_jwt = true
import_map = "deno.json"
entrypoint = "index.ts"

[functions.generate-infrastructure]
enabled = true
verify_jwt = true
import_map = "deno.json"
entrypoint = "index.ts"
