
app = "keight-deployment-worker"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  NODE_OPTIONS = "--dns-result-order=ipv4first"
  BUN_CONFIG_NO_CLEAR_TERMINAL = "true"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 15
    soft_limit = 10

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[deploy]
  strategy = "immediate"

[http_service]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1

[vm]
  memory = "2gb"
  cpus = 2
