// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfezwmgsudmthpcjpbdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmZXp3bWdzdWRtdGhwY2pwYmRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjI4NDcsImV4cCI6MjA2NDAzODg0N30.JsTpF3vwnUr9QEVMtuiAoKNR8JZ9WRCJqMMWX8yeavU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);